export const cartActionTypes ={
    ADD_ITEM : "ADD_ITEM",
    REMOVE_ITEM : "REMOVE_ITEM",
    CHANGE_TAX: "CHANGE_TAX",
    CHANGE_DISCOUNT: "CHANGE_DISCOUNT",
    TOGGLE_DRAWER: "TOGGLE_DRAWER",
    CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FORM_CART",
    CLEAR_CART: "CLEAR_CART"
}